apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: zuul-config
spec:
  runPolicy: Serial
  source:
      git:
        ref: main
        uri: 'https://github.com/eduardo-lr/spring-boot-zuul.git'
      type: Git
  strategy:
      dockerStrategy:
      type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'zuul-image:latest'
  triggers:
    - type: ConfigChange