apiVersion: v1
kind: Service
metadata:
  name: servicio-zuul-server  
spec:
  selector:                  
    deploymentconfig: zuul-deployment
  ports:
  - name: 8090-tcp
    port: 8090               
    protocol: TCP
    targetPort: 8090 